export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const AUTH_FAILED = "AUTH_FAIL";
export const AUTH_CHECK_STARTED = "AUTH_CHECK_STARTED";
export const AUTH_CHECK_SUCCESS = "AUTH_CHECK_SUCCESS";
