export const ACTIVE_USER_LOADING_STARTED = "ACTIVE_USER_LOADING_STARTED";
export const ACTIVE_USER_LOADED = "ACTIVE_USER_LOADED";
export const ACTIVE_USER_LOADING_FAILED = "ACTIVE_USER_LOADING_FAILED";
export const CLEAR_ACTIVE_USER = "CLEAR_ACTIVE_USER";
export const FETCH_ACTIVE_USER_LIKED_ARTICLES_STARTED =
  "FETCH_ACTIVE_USER_LIKED_ARTICLES_STARTED";
export const FETCH_ACTIVE_USER_LIKED_ARTICLES_SUCCESS =
  "FETCH_ACTIVE_USER_LIKED_ARTICLES_SUCCESS";
export const FETCH_ACTIVE_USER_LIKED_ARTICLES_FAILURE =
  "FETCH_ACTIVE_USER_LIKED_ARTICLES_FAILURE";
