export const FETCH_ARTICLE_STARTED = "FETCH_ARTICLE_STARTED";
export const FETCH_ARTICLE_SUCCESS = "FETCH_ARTICLE_SUCCESS";
export const FETCH_ARTICLE_FAILURE = "FETCH_ARTICLE_FAILURE";
export const FETCH_PREVIEW_LIST_STARTED = "FETCH_PREVIEW_LIST_STARTED";
export const FETCH_PREVIEW_LIST_SUCCESS = "FETCH_PREVIEW_LIST_SUCCESS";
export const FETCH_PREVIEW_LIST_FAILURE = "FETCH_PREVIEW_LIST_FAILURE";
export const FETCH_SEARCH_PREVIEW_LIST_STARTED =
  "FETCH_SEARCH_PREVIEW_LIST_STARTED";
export const FETCH_SEARCH_PREVIEW_LIST_SUCCESS =
  "FETCH_SEARCH_PREVIEW_LIST_SUCCESS";
export const FETCH_SEARCH_PREVIEW_LIST_FAILURE =
  "FETCH_SEARCH_PREVIEW_LIST_FAILURE";
export const SET_FILTER_TITLE = "SET_FILTER_TITLE";
export const SET_ARTICLES_PAGE = "SET_ARTICLES_PAGE";
export const SET_ARTICLES_PER_PAGE = "SET_ARTICLES_PER_PAGE";
export const SET_WITH_TAG = "SET_WITH_TAG";
export const SET_ORDERED_BY = "SET_ORDERED_BY";
export const SET_ORDER = "SET_ORDER";
